import Head from "next/head";
import styles from "./MainLayout.module.css";
import {NavBar} from "../NavBar"
import { FC } from "react";


export const MainLayout: FC = ({children}) => {
    return (
        <div className={styles.container}>
          <Head>
            <title>Home Page</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <NavBar />
    
          <main className={styles.main}>
                {children}
          </main>
    
        </div>
      )
}
